### ISSUE TITLE
Split and timew

### ISSUE THREAD

**Issue by rafaeluriarte** [cf020031308/pomodoro-warriors#3]
Thank you for your work. I am trying to make it work but after installing it (yes the scripts and hooks are in the right places) the command task still treats "split" and "timew" options as if they did not exists:

"task 8 split 'test'     
No matches."
"task 8 timew start pomodoro
No matches."

Any idea?

Thank you

**Comment by cf020031308** [comment]
I am not very sure since I have looked around but have found nothing.

But once I met something similar when using timewarrior that without permission to execute those extensions they were treated as if they did not exist.

So maybe you should check your permissions like:

1. Are those hooks and extensions executable?
2. Does the user who execute `task` or `timew` has the permission to reach those scripts?

**Comment by rafaeluriarte** [comment]
Thank you for the ideas. Actually I just noticed that the scripts start with /usr/bin/local/python, which is not correct in arch linux. I changed them to #!/usr/bin/python2 (I believe they use python2 not python3, correct?).  Yet, taskwarrior still treats the extensions as if they did not exists. When I execute the on-exit.py from command line it shows:

Traceback (most recent call last):
  File "./on-exit.py", line 52, in <module>
    main()
  File "./on-exit.py", line 13, in main
    inputs = utils.format_inputs()
  File "/home/rafael/tmp/pomo_warriors/pomodoro-warriors/taskwarrior/hooks/utils.py", line 39, in format_inputs
    assert inputs['api'] == '2', 'API: %s is not supported' % inputs['api']
KeyError: 'api'

Ideas?
